import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          emerald: "#064E3B",
          "emerald-dim": "#022c22",
          gold: "#D4AF37",
          cream: "#FAF9F6",
        },
        primary: "#003527",
        "on-primary": "#ffffff",
        "primary-container": "#064e3b",
        "on-primary-container": "#80bea6",
        "primary-fixed": "#b0f0d6",
        "primary-fixed-dim": "#95d3ba",
        "on-primary-fixed": "#002117",
        "on-primary-fixed-variant": "#0b513d",
        "inverse-primary": "#95d3ba",
        secondary: "#735c00",
        "on-secondary": "#ffffff",
        "secondary-container": "#fed65b",
        "on-secondary-container": "#745c00",
        "secondary-fixed": "#ffe088",
        "secondary-fixed-dim": "#e9c349",
        "on-secondary-fixed": "#241a00",
        "on-secondary-fixed-variant": "#574500",
        tertiary: "#2d2e2c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#434442",
        "on-tertiary-container": "#b1b1ae",
        "tertiary-fixed": "#e3e2e0",
        "tertiary-fixed-dim": "#c7c6c4",
        "on-tertiary-fixed": "#1a1c1a",
        "on-tertiary-fixed-variant": "#464745",
        surface: "#f8f9ff",
        "surface-dim": "#d0dbed",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dee9fc",
        "surface-container-highest": "#d9e3f6",
        "on-surface": "#121c2a",
        "on-surface-variant": "#404944",
        "inverse-surface": "#27313f",
        "inverse-on-surface": "#eaf1ff",
        "surface-variant": "#d9e3f6",
        "surface-tint": "#2b6954",
        outline: "#707974",
        "outline-variant": "#bfc9c3",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f8f9ff",
        foreground: "#121c2a",
        "secondary-highlight": "#D4AF37",
      },
      borderRadius: {
        xl: "24px",
        lg: "12px",
        "2xl": "32px",
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)"],
        mono: ["var(--font-geist-mono)"],
      },
    },
  },
  plugins: [],
};
export default config;
